import React from "react";
import {
  Zap,
  Droplets,
  Hammer,
  Flame,
  PaintRoller,
  Car,
  Cpu,
  Construction,
  Sparkles,
  Trees,
  WashingMachine,
  MoreHorizontal,
} from "lucide-react";

export const CATEGORIES = [
  {
    id: "electrician",
    label: "Electrician",
    icon: Zap,
    color: "text-amber-500",
    bg: "bg-amber-50",
  },
  {
    id: "plumber",
    label: "Plumber",
    icon: Droplets,
    color: "text-sky-500",
    bg: "bg-sky-50",
  },
  {
    id: "carpenter",
    label: "Carpenter",
    icon: Hammer,
    color: "text-orange-500",
    bg: "bg-orange-50",
  },
  {
    id: "welder",
    label: "Welder",
    icon: Flame,
    color: "text-red-500",
    bg: "bg-red-50",
  },
  {
    id: "painter",
    label: "Painter",
    icon: PaintRoller,
    color: "text-pink-500",
    bg: "bg-pink-50",
  },
  {
    id: "mechanic",
    label: "Mechanic",
    icon: Car,
    color: "text-slate-600",
    bg: "bg-slate-100",
  },
  {
    id: "technician",
    label: "Technician",
    icon: Cpu,
    color: "text-violet-500",
    bg: "bg-violet-50",
  },
  {
    id: "mason",
    label: "Mason",
    icon: Construction,
    color: "text-stone-500",
    bg: "bg-stone-100",
  },
  {
    id: "cleaner",
    label: "House Cleaner",
    icon: Sparkles,
    color: "text-teal-500",
    bg: "bg-teal-50",
  },
  {
    id: "gardener",
    label: "Gardener",
    icon: Trees,
    color: "text-green-600",
    bg: "bg-green-50",
  },
  {
    id: "appliance",
    label: "Appliance Repair",
    icon: WashingMachine,
    color: "text-indigo-500",
    bg: "bg-indigo-50",
  },
  {
    id: "other",
    label: "More Services",
    icon: MoreHorizontal,
    color: "text-muted-foreground",
    bg: "bg-muted",
  },
];
